sudo: required

env:
  global:
    - MYSQL_DATABASE: test
    - MYSQL_ROOT_PASSWORD: root
    - MYSQL_USER: dev
    - MYSQL_PASSWORD: dev

services:
  - docker

before_install:
  - mv .env.dist .env

install:
  - docker-compose up -d
  - docker-compose ps

before_script:
  - docker-compose run phpfpm composer update

script:
  - docker-compose run phpfpm ./vendor/bin/phpunit ./tests