sudo: required

env:
  global:
    - MYSQL_DATABASE: test
    - MYSQL_ROOT_PASSWORD: root
    - MYSQL_USER: dev
    - MYSQL_PASSWORD: dev

services:
  - docker

before_install:
  - mv .env.dist .env

install:
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps

before_script:
  - docker-compose run --rm phpfpm bash -c "cd test/ && composer update"

script:
  - docker-compose run --rm phpfpm bash -c "cd test/ && ./vendor/bin/phpunit ./tests"