version: '3'
 
services:

  nginx:
    build: services/nginx
    container_name: nginx
    restart: always
    working_dir: /www
    volumes:
      - ./web:/www
    ports:
      - 80:80
  
  php-fpm:
    build: services/phpfpm
    container_name: phpfpm
    restart: always
    working_dir: /www
    volumes:
      - ./web:/www
  

