version: '3'
 
services:

  mysql:
    build: services/mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./services/mysql/data/:/var/lib/mysql:rw
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    build: services/phpmyadmin
    container_name: phpmyadmin
    restart: always
    env_file:
      - ./.env
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PORT=${MYSQL_PORT}
    ports:
      - ${PMA_PORT}:80
    depends_on:
      - mysql

  nginx:
    build: services/nginx
    container_name: nginx
    restart: always
    working_dir: /www
    volumes:
      - ./web:/www
    env_file:
      - ./.env
    ports:
      - ${NGINX_PORT}:80

  phpfpm:
    build: services/phpfpm
    container_name: phpfpm
    restart: always
    working_dir: /www
    volumes:
      - ./web:/www
